
# Security Level Mappings
NO_AUTH_OR_PRIVACY = 1
AUTH_WITHOUT_PRIVACY = 2
AUTH_WITH_PRIVACY = 3

# SNMP Type
NO_SUCH_OBJECT = 'NOSUCHOBJECT'
NO_SUCH_INSTANCE = 'NOSUCHINSTANCE'

# SNMP Session
DEFAULT_VERSION = 3